all:
	g++ -std=c++11 RoadsAndJunctions.cpp

vis:
	java -jar tester.jar -exec "./a.out" -seed ${seed} -debug

test:
	java -jar tester.jar -exec "./a.out" -seed 1 -novis
	java -jar tester.jar -exec "./a.out" -seed 2 -novis
	java -jar tester.jar -exec "./a.out" -seed 3 -novis
	java -jar tester.jar -exec "./a.out" -seed 4 -novis
	java -jar tester.jar -exec "./a.out" -seed 5 -novis
	java -jar tester.jar -exec "./a.out" -seed 6 -novis
	java -jar tester.jar -exec "./a.out" -seed 7 -novis
	java -jar tester.jar -exec "./a.out" -seed 8 -novis
	java -jar tester.jar -exec "./a.out" -seed 9 -novis
	java -jar tester.jar -exec "./a.out" -seed 10 -novis
	java -jar tester.jar -exec "./a.out" -seed 11 -novis
	java -jar tester.jar -exec "./a.out" -seed 12 -novis
	java -jar tester.jar -exec "./a.out" -seed 13 -novis
	java -jar tester.jar -exec "./a.out" -seed 14 -novis
	java -jar tester.jar -exec "./a.out" -seed 15 -novis
	java -jar tester.jar -exec "./a.out" -seed 16 -novis
	java -jar tester.jar -exec "./a.out" -seed 17 -novis
	java -jar tester.jar -exec "./a.out" -seed 18 -novis
	java -jar tester.jar -exec "./a.out" -seed 19 -novis
	java -jar tester.jar -exec "./a.out" -seed 20 -novis
	java -jar tester.jar -exec "./a.out" -seed 21 -novis
	java -jar tester.jar -exec "./a.out" -seed 22 -novis
	java -jar tester.jar -exec "./a.out" -seed 23 -novis
	java -jar tester.jar -exec "./a.out" -seed 24 -novis
	java -jar tester.jar -exec "./a.out" -seed 25 -novis
	java -jar tester.jar -exec "./a.out" -seed 26 -novis
	java -jar tester.jar -exec "./a.out" -seed 27 -novis
	java -jar tester.jar -exec "./a.out" -seed 28 -novis
	java -jar tester.jar -exec "./a.out" -seed 29 -novis
	java -jar tester.jar -exec "./a.out" -seed 30 -novis
	java -jar tester.jar -exec "./a.out" -seed 31 -novis
	java -jar tester.jar -exec "./a.out" -seed 32 -novis
	java -jar tester.jar -exec "./a.out" -seed 33 -novis
	java -jar tester.jar -exec "./a.out" -seed 34 -novis
	java -jar tester.jar -exec "./a.out" -seed 35 -novis
	java -jar tester.jar -exec "./a.out" -seed 36 -novis
	java -jar tester.jar -exec "./a.out" -seed 37 -novis
	java -jar tester.jar -exec "./a.out" -seed 38 -novis
	java -jar tester.jar -exec "./a.out" -seed 39 -novis
	java -jar tester.jar -exec "./a.out" -seed 40 -novis
	java -jar tester.jar -exec "./a.out" -seed 41 -novis
	java -jar tester.jar -exec "./a.out" -seed 42 -novis
	java -jar tester.jar -exec "./a.out" -seed 43 -novis
	java -jar tester.jar -exec "./a.out" -seed 44 -novis
	java -jar tester.jar -exec "./a.out" -seed 45 -novis
	java -jar tester.jar -exec "./a.out" -seed 46 -novis
	java -jar tester.jar -exec "./a.out" -seed 47 -novis
	java -jar tester.jar -exec "./a.out" -seed 48 -novis
	java -jar tester.jar -exec "./a.out" -seed 49 -novis
	java -jar tester.jar -exec "./a.out" -seed 50 -novis
	java -jar tester.jar -exec "./a.out" -seed 51 -novis
	java -jar tester.jar -exec "./a.out" -seed 52 -novis
	java -jar tester.jar -exec "./a.out" -seed 53 -novis
	java -jar tester.jar -exec "./a.out" -seed 54 -novis
	java -jar tester.jar -exec "./a.out" -seed 55 -novis
	java -jar tester.jar -exec "./a.out" -seed 56 -novis
	java -jar tester.jar -exec "./a.out" -seed 57 -novis
	java -jar tester.jar -exec "./a.out" -seed 58 -novis
	java -jar tester.jar -exec "./a.out" -seed 59 -novis
	java -jar tester.jar -exec "./a.out" -seed 60 -novis
	java -jar tester.jar -exec "./a.out" -seed 61 -novis
	java -jar tester.jar -exec "./a.out" -seed 62 -novis
	java -jar tester.jar -exec "./a.out" -seed 63 -novis
	java -jar tester.jar -exec "./a.out" -seed 64 -novis
	java -jar tester.jar -exec "./a.out" -seed 65 -novis
	java -jar tester.jar -exec "./a.out" -seed 66 -novis
	java -jar tester.jar -exec "./a.out" -seed 67 -novis
	java -jar tester.jar -exec "./a.out" -seed 68 -novis
	java -jar tester.jar -exec "./a.out" -seed 69 -novis
	java -jar tester.jar -exec "./a.out" -seed 70 -novis
	java -jar tester.jar -exec "./a.out" -seed 71 -novis
	java -jar tester.jar -exec "./a.out" -seed 72 -novis
	java -jar tester.jar -exec "./a.out" -seed 73 -novis
	java -jar tester.jar -exec "./a.out" -seed 74 -novis
	java -jar tester.jar -exec "./a.out" -seed 75 -novis
	java -jar tester.jar -exec "./a.out" -seed 76 -novis
	java -jar tester.jar -exec "./a.out" -seed 77 -novis
	java -jar tester.jar -exec "./a.out" -seed 78 -novis
	java -jar tester.jar -exec "./a.out" -seed 79 -novis
	java -jar tester.jar -exec "./a.out" -seed 80 -novis
	java -jar tester.jar -exec "./a.out" -seed 81 -novis
	java -jar tester.jar -exec "./a.out" -seed 82 -novis
	java -jar tester.jar -exec "./a.out" -seed 83 -novis
	java -jar tester.jar -exec "./a.out" -seed 84 -novis
	java -jar tester.jar -exec "./a.out" -seed 85 -novis
	java -jar tester.jar -exec "./a.out" -seed 86 -novis
	java -jar tester.jar -exec "./a.out" -seed 87 -novis
	java -jar tester.jar -exec "./a.out" -seed 88 -novis
	java -jar tester.jar -exec "./a.out" -seed 89 -novis
	java -jar tester.jar -exec "./a.out" -seed 90 -novis
	java -jar tester.jar -exec "./a.out" -seed 91 -novis
	java -jar tester.jar -exec "./a.out" -seed 92 -novis
	java -jar tester.jar -exec "./a.out" -seed 93 -novis
	java -jar tester.jar -exec "./a.out" -seed 94 -novis
	java -jar tester.jar -exec "./a.out" -seed 95 -novis
	java -jar tester.jar -exec "./a.out" -seed 96 -novis
	java -jar tester.jar -exec "./a.out" -seed 97 -novis
	java -jar tester.jar -exec "./a.out" -seed 98 -novis
	java -jar tester.jar -exec "./a.out" -seed 99 -novis
	java -jar tester.jar -exec "./a.out" -seed 100 -novis
